---
# handlers file for haproxy
- name: restart rsyslog
  service:
    name: rsyslog
    state: started
    enabled: yes

- name: restart haproxy
  service:
    name: haproxy
    state: started
    enabled: yes

